export const ArticleDesign = {
	Standard: 0,
	Media: 1,
	Review: 2,
	Analysis: 3,
	Comment: 4,
	Letter: 5,
	Feature: 6,
	LiveBlog: 7,
	DeadBlog: 8,
	Recipe: 9,
	MatchReport: 10,
	Interview: 11,
	Editorial: 12,
	Quiz: 13,
	Interactive: 14,
	PhotoEssay: 15,
	PrintShop: 16,
	Obituary: 17,
	Correction: 18,
	FullPageInteractive: 19,
	NewsletterSignup: 20,
} as const;
