name: PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-release:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
